import { useState } from 'react';

type GeneratedAnswer = { answer: string; versionNumber: number; charCount: number; byteCount: number; warnings: string[]; unsupportedClaims: string[]; limitStatus: { isExceeded: boolean } };

export function AiAnswerGenerator({ questionId, disabled, onApply }: { questionId?: number; disabled: boolean; onApply: (answer: string) => void }) {
  const [loading, setLoading] = useState(false); const [result, setResult] = useState<GeneratedAnswer | null>(null); const [message, setMessage] = useState('');
  async function generate() { if (!questionId) { setMessage('자소서를 먼저 저장한 뒤 AI 초안을 만들 수 있습니다.'); return; } setLoading(true); setMessage(''); try { const response = await fetch('/api/ai/generate-answer', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ resumeQuestionId: questionId }) }); const body = await response.json() as { ok: boolean; data?: GeneratedAnswer; error?: string }; if (!response.ok || !body.ok || !body.data) throw new Error(body.error || 'AI 초안을 생성하지 못했습니다.'); setResult(body.data); } catch (error) { setMessage(error instanceof Error ? error.message : 'AI 초안을 생성하지 못했습니다.'); } finally { setLoading(false); } }
  const checks = result ? [...result.warnings, ...result.unsupportedClaims] : [];
  return <div className="mt-3"><button type="button" disabled={disabled || loading} onClick={()=>void generate()} className="rounded-lg bg-violet-700 px-3 py-2 text-xs font-medium text-white disabled:bg-violet-300">{loading ? '초안 작성 중...' : 'AI 초안 만들기'}</button>{message ? <p className="mt-2 text-xs text-red-700">{message}</p> : null}{result ? <div className="mt-3 rounded-xl border border-violet-200 bg-violet-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-xs text-violet-800">AI 초안 · {result.charCount}자 / {result.byteCount}byte{result.limitStatus.isExceeded ? ' · 제한 초과' : ''}</span><button type="button" onClick={()=>onApply(result.answer)} className="rounded-lg bg-neutral-950 px-3 py-2 text-xs font-medium text-white">답변에 적용</button></div><p className="mt-3 whitespace-pre-line text-sm leading-7 text-neutral-800">{result.answer}</p>{checks.length ? <details className="mt-3 text-xs text-neutral-600"><summary className="cursor-pointer">확인 사항 {checks.length}개</summary><ul className="mt-2 list-disc space-y-1 pl-4">{checks.map((item)=><li key={item}>{item}</li>)}</ul></details> : null}<p className="mt-3 text-xs text-neutral-500">적용 후 자소서 저장을 눌러 반영하세요.</p></div> : null}</div>;
}
