import { useState } from 'react';

type GeneratedAnswer = { answer: string; versionNumber: number; charCount: number; byteCount: number; usedFacts: string[]; warnings: string[]; unsupportedClaims: string[]; limitStatus: { type: 'chars' | 'bytes' | 'none'; limit: number | null; current: number; isExceeded: boolean } };

export function AiAnswerGenerator({ questionId, disabled, onApply }: { questionId?: number; disabled: boolean; onApply: (answer: string) => void }) {
  const [loading, setLoading] = useState(false); const [result, setResult] = useState<GeneratedAnswer | null>(null); const [message, setMessage] = useState('');
  async function generate() { if (!questionId) { setMessage('자소서를 먼저 저장한 뒤 AI 작성을 사용할 수 있습니다.'); return; } setLoading(true); setMessage(''); try { const response = await fetch('/api/ai/generate-answer', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ resumeQuestionId: questionId }) }); const body = await response.json() as { ok: boolean; data?: GeneratedAnswer; error?: string }; if (!response.ok || !body.ok || !body.data) throw new Error(body.error || 'AI 초안을 생성하지 못했습니다.'); setResult(body.data); } catch (error) { setMessage(error instanceof Error ? error.message : 'AI 초안을 생성하지 못했습니다.'); } finally { setLoading(false); } }
  return <div className="mt-3 rounded-2xl border border-violet-200 bg-violet-50 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-sm font-medium text-violet-950">AI로 자소서 작성</div><p className="mt-1 text-xs leading-5 text-violet-800">연결한 경험카드·스토리·확인된 성과만 사용합니다. 기존 답변은 바꾸지 않고 새 버전으로 제안합니다.</p></div><button type="button" disabled={disabled || loading} onClick={()=>void generate()} className="rounded-xl bg-violet-700 px-3 py-2 text-xs font-medium text-white disabled:bg-violet-300">{loading ? '작성 중...' : 'AI 초안 만들기'}</button></div>{message ? <p className="mt-3 text-xs text-red-700">{message}</p> : null}{result ? <div className="mt-4 rounded-2xl bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="text-xs text-neutral-500">AI 초안 v{result.versionNumber} · {result.charCount}자 / {result.byteCount}byte{result.limitStatus.isExceeded ? ' · 제한 초과' : ''}</div><button type="button" onClick={()=>onApply(result.answer)} className="rounded-xl bg-black px-3 py-2 text-xs font-medium text-white">답변에 적용</button></div><p className="mt-3 whitespace-pre-line text-sm leading-7 text-neutral-800">{result.answer}</p>{result.warnings.length ? <div className="mt-3 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">{result.warnings.map((warning)=><p key={warning}>• {warning}</p>)}</div> : null}{result.unsupportedClaims.length ? <div className="mt-3 rounded-xl bg-red-50 p-3 text-xs text-red-800">근거 확인 필요: {result.unsupportedClaims.join(' · ')}</div> : null}<p className="mt-3 text-xs text-neutral-500">`답변에 적용` 후 기존 저장 버튼을 눌러야 실제 자소서 답변에 반영됩니다.</p></div> : null}</div>;
}
