import { useEffect, useState } from 'react';
import { listExperienceCards } from '../experience-cards/api';
import type { ExperienceCard } from '../experience-cards/types';
import { CategoryBadge } from '../experience-cards/badges';

type Link = { id?: number; experience_card_id: number; is_primary: boolean; experience_title?: string; category?: string };
async function loadLinks(questionId: number) { const response = await fetch(`/api/resume-question-experience-links?questionId=${questionId}`); const body = await response.json() as { ok: boolean; data?: Link[]; error?: string }; if (!response.ok || !body.ok) throw new Error(body.error || '선택한 경험을 불러오지 못했습니다.'); return body.data || []; }

export function ResumeExperienceLinks({ questionId, disabled }: { questionId?: number; disabled: boolean }) {
  const [links, setLinks] = useState<Link[]>([]); const [cards, setCards] = useState<ExperienceCard[]>([]); const [isOpen, setIsOpen] = useState(false); const [loading, setLoading] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { if (!questionId || disabled) { setLinks([]); return; } void loadLinks(questionId).then(setLinks).catch((error) => setMessage(error instanceof Error ? error.message : '')); }, [questionId, disabled]);
  async function openPicker() { if (!questionId) { setMessage('자소서를 먼저 저장한 뒤 경험을 선택할 수 있습니다.'); return; } setLoading(true); try { const [savedLinks, data] = await Promise.all([loadLinks(questionId), listExperienceCards()]); setLinks(savedLinks); setCards(data.items.filter((card) => card.status !== 'archived')); setIsOpen(true); } catch (error) { setMessage(error instanceof Error ? error.message : '경험을 불러오지 못했습니다.'); } finally { setLoading(false); } }
  async function save(next: Link[]) { if (!questionId) return; setLoading(true); try { const response = await fetch('/api/resume-question-experience-links', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ questionId, links: next.map((link, index) => ({ experience_card_id: link.experience_card_id, story_angle_id: null, is_primary: index === 0, note: '' })) }) }); const body = await response.json() as { ok: boolean; data?: Link[]; error?: string }; if (!response.ok || !body.ok) throw new Error(body.error || '경험을 저장하지 못했습니다.'); setLinks(body.data || []); } catch (error) { setMessage(error instanceof Error ? error.message : '경험을 저장하지 못했습니다.'); } finally { setLoading(false); } }
  function toggle(card: ExperienceCard) { const selected = links.some((link) => link.experience_card_id === card.id); if (selected) { void save(links.filter((link) => link.experience_card_id !== card.id)); return; } if (links.length >= 3) { setMessage('문항에는 경험을 최대 3개까지 선택할 수 있습니다.'); return; } void save([...links, { experience_card_id: card.id, is_primary: links.length === 0, experience_title: card.title, category: card.category }]); }
  return <div className="rounded-lg border border-neutral-200 bg-white p-3"><div className="flex items-center justify-between gap-3"><div><div className="text-sm font-medium">사용할 경험</div><p className="mt-1 text-xs text-neutral-500">핵심 경험 하나만 선택해도 충분합니다.</p></div><button type="button" disabled={disabled || loading} onClick={()=>void openPicker()} className="rounded-md border border-neutral-200 px-3 py-2 text-xs font-medium disabled:opacity-40">{loading ? '불러오는 중...' : '경험 선택'}</button></div>{links.length ? <div className="mt-3 flex flex-wrap gap-2">{links.map((link) => <span key={link.id || link.experience_card_id} className="inline-flex items-center gap-2 rounded-md bg-neutral-100 px-3 py-2 text-xs"><b>{link.is_primary ? '핵심' : '보조'}</b>{link.experience_title || `경험 #${link.experience_card_id}`}<button type="button" onClick={()=>void save(links.filter((item) => item.experience_card_id !== link.experience_card_id))} className="text-neutral-500">×</button></span>)}</div> : null}{message ? <p className="mt-3 text-xs text-neutral-500">{message}</p> : null}{isOpen ? <div className="mt-4 border-t border-neutral-100 pt-4"><div className="max-h-60 space-y-2 overflow-y-auto">{cards.map((card) => { const selected = links.some((link) => link.experience_card_id === card.id); return <button type="button" key={card.id} onClick={() => toggle(card)} className={`w-full rounded-md border p-3 text-left ${selected ? 'border-neutral-950 bg-neutral-950 text-white' : 'border-neutral-200 bg-white'}`}><div className="text-sm font-medium">{card.title}</div><div className="mt-1 flex flex-wrap items-center gap-2 text-xs"><CategoryBadge category={card.category} />{card.summary ? <span className={selected ? 'text-neutral-300' : 'text-neutral-500'}>{card.summary}</span> : null}</div></button>; })}</div><button type="button" onClick={()=>setIsOpen(false)} className="mt-3 text-xs text-neutral-500 underline">닫기</button></div> : null}</div>;
}
